const DIRECTION_KEYBOARD_BUTTONS = ['ArrowDown', 'ArrowUp', 'ArrowLeft', 'ArrowRight'];
const KEYBOARD_ACTION_BUTTONS = ['Enter'];

const DIRECTION_GAMEPAD_BUTTONS = ['12','13','14','15'];
const GAMEPAD_ACTION_BUTTONS = ['1'];

export {
    DIRECTION_KEYBOARD_BUTTONS,
    KEYBOARD_ACTION_BUTTONS,
    DIRECTION_GAMEPAD_BUTTONS,
    GAMEPAD_ACTION_BUTTONS,
}
